---
- name: >
    pay for ios devices
    that use ios_facts
  hosts: switch
  gather_facts: no
  tasks:
    - name: look at some facts
      ios_facts:
        gather_subset:
          - hardware
    - name: show results
      debug:
        msg:
          - "file system: {{ ansible_net_filesystems }}"
          - "free mem MB: {{ ansible_net_memfree_mb }}"
          - "mem total MB: {{ ansible_net_memtotal_mb }}"

