---
- name: a reachability test
  hosts: switch
  vars_files:
    - vars/myvars.yml

  tasks:
    - name: test reachability to 8.8.8.8
      ios_ping:
        dest: "{{ item }}"
      loop: "{{ ipv4_addresses | select('match','^8\\.8\\.8\\..*') | list }}"
      when: ansible_network_os == 'ios'
